In [8]:
import pandas as pd

df = pd.read_csv("/Users/maxliuuu/Desktop/BLcombo.csv")

df.head()

,Date,Time,Category,Item,Qty,Price Point Name,Business_Group,Gross Sales,Discounts,Net Sales,Tax,Transaction ID,Location
0,7/15/26,22:13:07,Pepsi,Bottled Beverages,1,Fruit Punch Gatorade,Non-Alcoholic Beverage,$5.00,$0.00,$5.00,$0.00,f1bT3f1fCVzypOuR8TZll23GagRZY,Main Stand 2
1,7/15/26,22:09:16,Pepsi,Bottled Beverages,1,Aquifina,Non-Alcoholic Beverage,$5.00,$0.00,$5.00,$0.00,90NaCSOjLydoyxGRdYJyyE2GNjZZY,Main Stand 2
2,7/15/26,22:05:39,Pepsi,Bottled Beverages,1,Aquifina,Non-Alcoholic Beverage,$5.00,$0.00,$5.00,$0.00,P7ypSbGMkECojVIlYMm5Fp8oZZJZY,Main Stand 1
3,7/15/26,22:05:07,Food,Cotton Candy,1,Regular,Desserts,$7.00,$0.00,$7.00,$0.00,zDzOB2sh4eAnb0EvVVr3XzlUxCKZY,Main Stand 1
4,7/15/26,22:01:21,Food,Small Popcorn,1,Regular,Popcorn,$5.00,$0.00,$5.00,$0.00,dgXwQhEPYpsuYJlCqIcTZxIJTRUZY,Main Stand 1

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16755 entries, 0 to 16754
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              16755 non-null  object
 1   Time              16755 non-null  object
 2   Category          16755 non-null  object
 3   Item              16755 non-null  object
 4   Qty               16755 non-null  int64
 5   Price Point Name  16755 non-null  object
 6   Business_Group    16755 non-null  object
 7   Gross Sales       16755 non-null  object
 8   Discounts         16755 non-null  object
 9   Net Sales         16755 non-null  object
 10  Tax               16755 non-null  object
 11  Transaction ID    16755 non-null  object
 12  Location          16755 non-null  object
dtypes: int64(1), object(12)
memory usage: 1.7+ MB

In [10]:
print(df.columns)

Index(['Date', 'Time', 'Category', 'Item', 'Qty', 'Price Point Name',
       'Business_Group ', 'Gross Sales', 'Discounts', 'Net Sales', 'Tax',
       'Transaction ID', 'Location'],
      dtype='object')

In [11]:
grouped=df.groupby("Transaction ID")

In [12]:
grouped.size().mean()

np.float64(1.9170480549199085)

In [13]:
basket= (
    df.groupby("Transaction ID")["Business_Group "]
      .apply(list)
      .reset_index()
)

In [14]:
print(basket)

                     Transaction ID  \
0     105NTnaQq0r1Nrt5wbuOt78hpeIZY
1     10Fxm1az2usSgFgWsAkBxtdJVy7YY
2     10HEtWnl5toveXth4J459CWuRkSZY
3     10LeJE4IvicXjw8mOaAWBosEyYCZY
4     10LgeEZ3r6ZdC3SDmcYiJVMajucZY
...                             ...
8735  zz9hiOBOI0HG9U7rLRG0imFgHMXZY
8736  zzR3q1wOYSw7LNvfIZmATbaBoUdZY
8737  zzT8G4VvFCB1WrZn4Ob9UhjmOOVZY
8738  zzdHjP4ARmJW0LNPcIWd4a36nJ8YY
8739  zzhRheHtEOIQaVpZTmujHV501aWZY

                                        Business_Group
0                    [Hot Dogs, Non-Alcoholic Beverage]
1                                             [Popcorn]
2                                             [Popcorn]
3                              [Non-Alcoholic Beverage]
4                            [Desserts, Snacks, Snacks]
...                                                 ...
8735                                           [Snacks]
8736                           [Non-Alcoholic Beverage]
8737                       [Snacks, Alcoholic Beverage]
8738                                          [Popcorn]
8739  [Hot Dogs, Popcorn, Non-Alcoholic Beverage, Al...

[8740 rows x 2 columns]

In [15]:
!pip install mlxtend

Requirement already satisfied: mlxtend in /opt/anaconda3/lib/python3.13/site-packages (0.25.0)
Requirement already satisfied: scipy>=1.16.3 in /opt/anaconda3/lib/python3.13/site-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=2.3.5 in /opt/anaconda3/lib/python3.13/site-packages (from mlxtend) (2.3.5)
Requirement already satisfied: pandas>=2.3.3 in /opt/anaconda3/lib/python3.13/site-packages (from mlxtend) (2.3.3)
Requirement already satisfied: scikit-learn>=1.8.0 in /opt/anaconda3/lib/python3.13/site-packages (from mlxtend) (1.9.0)
Requirement already satisfied: matplotlib>=3.10.8 in /opt/anaconda3/lib/python3.13/site-packages (from mlxtend) (3.11.1)
Requirement already satisfied: joblib>=1.5.2 in /opt/anaconda3/lib/python3.13/site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.28.2 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (25.0)
Requirement already satisfied: pillow>=9 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn>=1.8.0->mlxtend) (2.7.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn>=1.8.0->mlxtend) (3.5.0)

In [16]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [17]:
te = TransactionEncoder()

te_array = te.fit(basket["Business_Group "]).transform(basket["Business_Group "])

basket_df = pd.DataFrame(
    te_array,
    columns=te.columns_
)

In [18]:
basket_df.head()

,Alcoholic Beverage,Beer,Burgers,Desserts,Hot Dogs,Nachos,Non-Alcoholic Beverage,Popcorn,Pretzels,Ready-to-Drink Alcohol,Sandwiches,Snacks
0,False,False,False,False,True,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,False,True

In [19]:
frequent_itemsets = apriori(
    basket_df,
    min_support=0.02,
    use_colnames=True
)

In [20]:
frequent_itemsets

     support                            itemsets
0   0.033982                (Alcoholic Beverage)
1   0.208238                              (Beer)
2   0.063043                           (Burgers)
3   0.183638                          (Desserts)
4   0.113959                          (Hot Dogs)
5   0.047140                            (Nachos)
6   0.310641            (Non-Alcoholic Beverage)
7   0.190732                           (Popcorn)
8   0.070938                          (Pretzels)
9   0.061785            (Ready-to-Drink Alcohol)
10  0.305263                            (Snacks)
11  0.027689                    (Hot Dogs, Beer)
12  0.042792      (Non-Alcoholic Beverage, Beer)
13  0.027689                     (Popcorn, Beer)
14  0.023570                      (Snacks, Beer)
15  0.020824                 (Burgers, Hot Dogs)
16  0.035812   (Non-Alcoholic Beverage, Burgers)
17  0.023570  (Non-Alcoholic Beverage, Desserts)
18  0.026087                 (Popcorn, Desserts)
19  0.052975                  (Snacks, Desserts)
20  0.064760  (Non-Alcoholic Beverage, Hot Dogs)
21  0.024828    (Nachos, Non-Alcoholic Beverage)
22  0.061327   (Non-Alcoholic Beverage, Popcorn)
23  0.028947  (Non-Alcoholic Beverage, Pretzels)
24  0.039703    (Snacks, Non-Alcoholic Beverage)
25  0.044622                   (Snacks, Popcorn)

In [21]:
rules = association_rules(
    frequent_itemsets,
    metric="lift",
    min_threshold=1
)

In [23]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Burgers),(Hot Dogs),0.063043,0.113959,0.020824,0.330309,2.898491,1.0,0.013639,1.323059,0.699064,0.133333,0.244176,0.256520
1,(Hot Dogs),(Burgers),0.113959,0.063043,0.020824,0.182731,2.898491,1.0,0.013639,1.146448,0.739235,0.133333,0.127741,0.256520
2,(Non-Alcoholic Beverage),(Burgers),0.310641,0.063043,0.035812,0.115285,1.828666,1.0,0.016228,1.059050,0.657354,0.105994,0.055757,0.341672
3,(Burgers),(Non-Alcoholic Beverage),0.063043,0.310641,0.035812,0.568058,1.828666,1.0,0.016228,1.595954,0.483644,0.105994,0.373415,0.341672
4,(Non-Alcoholic Beverage),(Hot Dogs),0.310641,0.113959,0.064760,0.208471,1.829358,1.0,0.029359,1.119405,0.657654,0.179968,0.106668,0.388372
5,(Hot Dogs),(Non-Alcoholic Beverage),0.113959,0.310641,0.064760,0.568273,1.829358,1.0,0.029359,1.596748,0.511669,0.179968,0.373727,0.388372
6,(Nachos),(Non-Alcoholic Beverage),0.047140,0.310641,0.024828,0.526699,1.695525,1.0,0.010185,1.456492,0.430506,0.074570,0.313419,0.303313
7,(Non-Alcoholic Beverage),(Nachos),0.310641,0.047140,0.024828,0.079926,1.695525,1.0,0.010185,1.035635,0.595063,0.074570,0.034409,0.303313
8,(Non-Alcoholic Beverage),(Pretzels),0.310641,0.070938,0.028947,0.093186,1.313622,1.0,0.006911,1.024534,0.346330,0.082090,0.023947,0.250625
9,(Pretzels),(Non-Alcoholic Beverage),0.070938,0.310641,0.028947,0.408065,1.313622,1.0,0.006911,1.164585,0.256975,0.082090,0.141325,0.250625